name: tie-e-commerce
version: '3.8'

services:
  user_api:
    container_name: e_commerce_user_api
    image: sidjaix/user-api:latest
    build:
      context: .
      dockerfile: ./User/Dockerfile
    ports:
      - '5001:80'
    #restart: always
    # depends_on:
    #   - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__UserApi=server=techitez_sqlserver;Initial Catalog=UserApiDb; user ID=SA; Password=Admin@123; TrustServerCertificate=true; MultipleActiveResultSets=True;
    networks:
      - techitez_network

  product_api:
    container_name: e_commerce_product_api
    image: sidjaix/product-api:latest
    build:
      context: .
      dockerfile: ./Product/Dockerfile
    ports:
      - '5002:80'
    #restart: always
    # depends_on:
    #   - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__ProductApi=server=techitez_sqlserver;Initial Catalog=ProductApiDb; user ID=SA; Password=Admin@123; TrustServerCertificate=true; MultipleActiveResultSets=True;
    networks:
      - techitez_network

  cart_api:
    container_name: e_commerce_cart_api
    image: sidjaix/cart-api:latest
    build:
      context: .
      dockerfile: ./Cart/Dockerfile
    ports:
      - '5003:80'
    #restart: always
    # depends_on:
    #   - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__CartApi=server=techitez_sqlserver;Initial Catalog=CartApiDb; user ID=SA; Password=Admin@123; TrustServerCertificate=true; MultipleActiveResultSets=True;
    networks:
      - techitez_network

  order_api:
    container_name: e_commerce_order_api
    image: sidjaix/order-api:latest
    build:
      context: .
      dockerfile: ./Order/Dockerfile
    ports:
      - '5004:80'
    #restart: always
    # depends_on:
    #   - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__OrderApi=server=techitez_sqlserver;Initial Catalog=OrderApiDb; user ID=SA; Password=Admin@123; TrustServerCertificate=true; MultipleActiveResultSets=True;
    networks:
      - techitez_network

  rabbit_mq:
    container_name: techitez_rabbitmqserver
    image: rabbitmq:3-management
    hostname: ecomm-rabbit-mq-server
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - techitez_network

  # e-commerce-web:
  #   container_name: e_commerce_web
  #   image: sidjaix/e-commerce-web:latest
  #   build:
  #     context: .
  #     dockerfile: ./UI/Dockerfile
  #   ports:
  #     - '5005:80'
  #   depends_on:
  #     - product_api
  #     - user_api
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Production
  #     - ServiceUrls__AuthApi='http://e_commerce_user_api'
  #     - ServiceUrls__ProductApi='http://e_commerce_product_api'
  #   networks:
  #     - techitez_network

  # sqlserver:
  #   container_name: techitez_sqlserver
  #   hostname: sqledge
  #   image: mcr.microsoft.com/azure-sql-edge
  #   environment:
  #     SA_PASSWORD: 'Admin@123'
  #     ACCEPT_EULA: '1'
  #   ports:
  #     - '1433:1433'
  #   volumes:
  #     - techitez-sqledge:/var/opt/mssql
  #   networks:
  #     - techitez_network

networks:
  techitez_network:
    driver: bridge
